import { DEFAULT_FONT_FAMILY } from '../fonts'
import type { Scene } from '../scene'

export const courseSprintScene: Scene = {
  version: 1,
  backgroundColor: '#4c1d95',
  backgroundOpacity: 1,
  elements: [
    {
      id: 'sprint-top-chip',
      name: '顶部标签底',
      type: 'rect',
      x: 274,
      y: 76,
      width: 394,
      height: 58,
      radius: 29,
      fill: '#22c55e',
      fillMode: 'gradient',
      gradient: {
        startColor: '#22c55e',
        endColor: '#a3e635',
        direction: 'horizontal',
      },
    },
    {
      id: 'sprint-top-chip-text',
      name: '顶部标签文字',
      type: 'text',
      text: '7 天实战训练营',
      x: 274,
      y: 92,
      width: 394,
      height: 32,
      fill: '#1e1b4b',
      fontSize: 30,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1,
    },
    {
      id: 'sprint-title',
      name: '训练营标题',
      type: 'text',
      text: 'AI 工具流\n从入门到交付',
      x: 106,
      y: 204,
      width: 730,
      height: 158,
      fill: '#ffffff',
      fontSize: 68,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1.16,
    },
    {
      id: 'sprint-subtitle',
      name: '训练营副标题',
      type: 'text',
      text: '适合产品、运营、教师与内容创作者',
      x: 126,
      y: 410,
      width: 690,
      height: 38,
      fill: '#ddd6fe',
      fontSize: 30,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 800,
      align: 'center',
      lineHeight: 1,
    },
    {
      id: 'sprint-video-left',
      name: '讲师视频占位',
      type: 'rect',
      x: 92,
      y: 530,
      width: 360,
      height: 580,
      radius: 20,
      fill: '#000000',
      stroke: '#ffffff',
      strokeWidth: 2,
      backgroundCutout: true,
    },
    {
      id: 'sprint-video-right',
      name: '助教视频占位',
      type: 'rect',
      x: 490,
      y: 530,
      width: 360,
      height: 580,
      radius: 20,
      fill: '#000000',
      stroke: '#ffffff',
      strokeWidth: 2,
      backgroundCutout: true,
    },
    {
      id: 'sprint-outline-card',
      name: '课程大纲底',
      type: 'rect',
      x: 92,
      y: 1202,
      width: 758,
      height: 228,
      radius: 22,
      fill: '#ffffff',
      opacity: 0.94,
    },
    {
      id: 'sprint-outline-title',
      name: '课程大纲标题',
      type: 'text',
      text: '本场你会带走',
      x: 132,
      y: 1240,
      width: 680,
      height: 38,
      fill: '#4c1d95',
      fontSize: 32,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'left',
      lineHeight: 1,
    },
    {
      id: 'sprint-outline',
      name: '课程大纲',
      type: 'text',
      text: '01 个人知识库搭建\n02 自动化内容生产\n03 真实业务交付演示',
      x: 132,
      y: 1300,
      width: 680,
      height: 102,
      fill: '#1f2937',
      fontSize: 28,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 800,
      align: 'left',
      lineHeight: 1.35,
    },
    {
      id: 'sprint-footer',
      name: '底部行动提示',
      type: 'text',
      text: '预约直播，领取课前资料包',
      x: 132,
      y: 1508,
      width: 678,
      height: 40,
      fill: '#ffffff',
      fontSize: 32,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1,
    },
  ],
}
