import { DEFAULT_FONT_FAMILY } from '../fonts'
import type { Scene } from '../scene'

export const launchPosterScene: Scene = {
  version: 1,
  backgroundColor: '#f8fafc',
  backgroundOpacity: 1,
  elements: [
    {
      id: 'poster-side-band',
      name: '左侧色带',
      type: 'rect',
      x: 0,
      y: 0,
      width: 110,
      height: 1672,
      fill: '#2563eb',
      fillMode: 'gradient',
      gradient: {
        startColor: '#2563eb',
        endColor: '#14b8a6',
        direction: 'vertical',
      },
    },
    {
      id: 'poster-label',
      name: '活动标签',
      type: 'text',
      text: '新课发布会',
      x: 160,
      y: 118,
      width: 320,
      height: 38,
      fill: '#2563eb',
      fontSize: 32,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'left',
      lineHeight: 1,
    },
    {
      id: 'poster-title',
      name: '海报标题',
      type: 'text',
      text: '用 AI 打造\n个人知识系统',
      x: 158,
      y: 214,
      width: 666,
      height: 172,
      fill: '#111827',
      fontSize: 72,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'left',
      lineHeight: 1.18,
    },
    {
      id: 'poster-subtitle',
      name: '海报副标题',
      type: 'text',
      text: '从信息收集、笔记整理到自动复盘',
      x: 164,
      y: 430,
      width: 628,
      height: 42,
      fill: '#475569',
      fontSize: 30,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 800,
      align: 'left',
      lineHeight: 1.2,
    },
    {
      id: 'poster-video',
      name: '主视觉视频占位',
      type: 'rect',
      x: 158,
      y: 558,
      width: 666,
      height: 648,
      radius: 26,
      fill: '#000000',
      stroke: '#111827',
      strokeWidth: 2,
      backgroundCutout: true,
    },
    {
      id: 'poster-card',
      name: '报名信息卡片',
      type: 'rect',
      x: 158,
      y: 1288,
      width: 666,
      height: 154,
      radius: 22,
      fill: '#111827',
    },
    {
      id: 'poster-date',
      name: '日期时间',
      type: 'text',
      text: '周四 20:00 直播',
      x: 198,
      y: 1328,
      width: 586,
      height: 42,
      fill: '#ffffff',
      fontSize: 38,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'left',
      lineHeight: 1,
    },
    {
      id: 'poster-note',
      name: '报名提示',
      type: 'text',
      text: '扫码预约，开播前自动提醒',
      x: 198,
      y: 1392,
      width: 586,
      height: 34,
      fill: '#cbd5e1',
      fontSize: 26,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 800,
      align: 'left',
      lineHeight: 1,
    },
  ],
}
