import { DEFAULT_FONT_FAMILY } from '../domain/fonts'
import type { Scene } from '../domain/scene'

export const roundtableScene: Scene = {
  version: 1,
  backgroundColor: '#2f244f',
  backgroundOpacity: 1,
  elements: [
    {
      id: 'roundtable-kicker',
      name: '栏目名称',
      type: 'text',
      text: 'Covercast Roundtable',
      x: 102,
      y: 86,
      width: 738,
      height: 32,
      fill: '#fcd34d',
      fontSize: 26,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1,
    },
    {
      id: 'roundtable-title',
      name: '圆桌标题',
      type: 'text',
      text: '三人圆桌：\nAI 产品如何落地？',
      x: 96,
      y: 142,
      width: 750,
      height: 136,
      fill: '#ffffff',
      fontSize: 58,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1.18,
    },
    {
      id: 'roundtable-video-left',
      name: '左上视频占位',
      type: 'rect',
      x: 72,
      y: 358,
      width: 380,
      height: 472,
      radius: 18,
      fill: '#000000',
      stroke: '#ffffff',
      strokeWidth: 2,
      backgroundCutout: true,
    },
    {
      id: 'roundtable-video-right',
      name: '右上视频占位',
      type: 'rect',
      x: 490,
      y: 358,
      width: 380,
      height: 472,
      radius: 18,
      fill: '#000000',
      stroke: '#ffffff',
      strokeWidth: 2,
      backgroundCutout: true,
    },
    {
      id: 'roundtable-video-bottom',
      name: '下方视频占位',
      type: 'rect',
      x: 168,
      y: 914,
      width: 606,
      height: 410,
      radius: 18,
      fill: '#000000',
      stroke: '#ffffff',
      strokeWidth: 2,
      backgroundCutout: true,
    },
    {
      id: 'roundtable-name-left',
      name: '左上嘉宾名',
      type: 'text',
      text: '嘉宾 A',
      x: 92,
      y: 852,
      width: 340,
      height: 42,
      fill: '#ffffff',
      fontSize: 34,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1,
    },
    {
      id: 'roundtable-name-right',
      name: '右上嘉宾名',
      type: 'text',
      text: '嘉宾 B',
      x: 510,
      y: 852,
      width: 340,
      height: 42,
      fill: '#ffffff',
      fontSize: 34,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1,
    },
    {
      id: 'roundtable-name-bottom',
      name: '下方嘉宾名',
      type: 'text',
      text: '主持人',
      x: 220,
      y: 1348,
      width: 502,
      height: 42,
      fill: '#ffffff',
      fontSize: 34,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1,
    },
    {
      id: 'roundtable-topic-card',
      name: '讨论话题底框',
      type: 'rect',
      x: 88,
      y: 1452,
      width: 766,
      height: 96,
      radius: 20,
      fill: '#fcd34d',
      fillMode: 'gradient',
      gradient: {
        startColor: '#fcd34d',
        endColor: '#f97316',
        direction: 'horizontal',
      },
    },
    {
      id: 'roundtable-topic',
      name: '讨论话题',
      type: 'text',
      text: '话题：增长、交付、团队协作',
      x: 88,
      y: 1482,
      width: 766,
      height: 42,
      fill: '#2f244f',
      fontSize: 34,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1,
    },
  ],
}
