import { DEFAULT_FONT_FAMILY } from '../fonts'
import type { Scene } from '../scene'

export const soloInterviewScene: Scene = {
  version: 1,
  backgroundColor: '#0f766e',
  backgroundOpacity: 1,
  elements: [
    {
      id: 'solo-host-avatar',
      name: '嘉宾头像',
      type: 'image',
      src: '',
      alt: '嘉宾头像',
      x: 70,
      y: 72,
      width: 106,
      height: 106,
      fit: 'cover',
      shape: 'circle',
      fallbackText: '嘉',
    },
    {
      id: 'solo-host-name',
      name: '嘉宾姓名',
      type: 'text',
      text: '主讲嘉宾',
      x: 198,
      y: 91,
      width: 260,
      height: 46,
      fill: '#ffffff',
      fontSize: 38,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'left',
      lineHeight: 1.1,
    },
    {
      id: 'solo-host-role',
      name: '嘉宾介绍',
      type: 'text',
      text: 'AI 教育实践者 / 直播间主持人',
      x: 200,
      y: 144,
      width: 470,
      height: 32,
      fill: '#ccfbf1',
      fontSize: 24,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 700,
      align: 'left',
      lineHeight: 1,
    },
    {
      id: 'solo-live-badge',
      name: '直播标签',
      type: 'rect',
      x: 676,
      y: 82,
      width: 166,
      height: 58,
      radius: 29,
      fill: '#f97316',
      fillMode: 'gradient',
      gradient: {
        startColor: '#f97316',
        endColor: '#facc15',
        direction: 'horizontal',
      },
    },
    {
      id: 'solo-live-text',
      name: '直播标签文字',
      type: 'text',
      text: 'LIVE',
      x: 676,
      y: 96,
      width: 166,
      height: 32,
      fill: '#ffffff',
      fontSize: 30,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1,
    },
    {
      id: 'solo-title',
      name: '主题标题',
      type: 'text',
      text: '如何用 AI\n升级学习效率',
      x: 104,
      y: 236,
      width: 734,
      height: 148,
      fill: '#ffffff',
      fontSize: 66,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1.18,
    },
    {
      id: 'solo-video',
      name: '单人视频占位',
      type: 'rect',
      x: 130,
      y: 440,
      width: 682,
      height: 780,
      radius: 20,
      fill: '#000000',
      stroke: '#ffffff',
      strokeWidth: 2,
      backgroundCutout: true,
    },
    {
      id: 'solo-name-card',
      name: '姓名底条',
      type: 'rect',
      x: 170,
      y: 1254,
      width: 602,
      height: 84,
      radius: 18,
      fill: '#ffffff',
      opacity: 0.95,
    },
    {
      id: 'solo-name-card-text',
      name: '姓名底条文字',
      type: 'text',
      text: '今晚 20:00 开播  |  预约直播间',
      x: 170,
      y: 1278,
      width: 602,
      height: 38,
      fill: '#0f766e',
      fontSize: 34,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 900,
      align: 'center',
      lineHeight: 1,
    },
    {
      id: 'solo-bottom-note',
      name: '底部提示',
      type: 'text',
      text: '适合单人访谈、公开课、开播预告',
      x: 120,
      y: 1452,
      width: 702,
      height: 42,
      fill: '#d1fae5',
      fontSize: 28,
      fontFamily: DEFAULT_FONT_FAMILY,
      fontWeight: 800,
      align: 'center',
      lineHeight: 1.2,
    },
  ],
}
